# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ad71179ffa4a76df41a9b7afbed89031"
name = "TiktokApp"
handle = "tiktokapp-5"
application_url = "https://nl-lion-ball-routing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "affan-test.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nl-lion-ball-routing.trycloudflare.com/auth/callback",
  "https://nl-lion-ball-routing.trycloudflare.com/auth/shopify/callback",
  "https://nl-lion-ball-routing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
