# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8c92bf1c7b84097f33c3cca54fe528ab"
application_url = "https://venues-vault-malta-friend.trycloudflare.com"
embedded = true
name = "TikTok_App"
handle = "tiktok_app"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "paymenttest-store.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_products,read_script_tags,read_themes,write_content,write_locales,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://venues-vault-malta-friend.trycloudflare.com/auth/callback",
  "https://venues-vault-malta-friend.trycloudflare.com/auth/shopify/callback",
  "https://venues-vault-malta-friend.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://venues-vault-malta-friend.trycloudflare.com/customapi"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
